#!/bin/sh

# ~/.xprofile @ celer
# read by xinit

# xdg environment variables
export XDG_DATA_DIRS="/media/felipe/applications/linux/share:$XDG_DATA_DIRS"
# Path environmet variables
export PATH="/media/frontier/applications/linux/binary/bin:$PATH"
# @see https://forums.gentoo.org/viewtopic-p-7080966.html
export VALAC=/usr/bin/valac-0.46

# i3 app Scale for 4k display  https://www.reddit.com/r/i3wm/comments/afk96e/i3wm_on_a_hdpi_screen/
export GDK_SCALE=2
export ELM_SCALE=2
export QT_AUTO_SCREEN_SCALE_FACTOR=1
